name: clean_architecture_tdd
description: A Clean Architecture and TDD project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.1
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  equatable: ^2.1.0
  dartz: ^0.10.1
  http: ^1.6.0
  shared_preferences: ^2.5.5
  internet_connection_checker_plus: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
